apiVersion: v1
kind: Service
metadata:
  {{ $relname := $.Release.Name}}
  name: {{ $relname }}-wordpress-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: {{ $relname }}-wordpress
  ports:
    - protocol: TCP
      port: {{ .Values.service.export_port }}
      targetPort: 80
      name: "{{ $relname }}-wordpress-{{ .Values.service.export_port }}"
  type: {{ .Values.service.type | default "ClusterIP" }}
